name: ${project.name}
version: ${project.version}
main: com.lenis0012.bukkit.loginsecurity.LoginSecurity
author: lenis0012
description: 'The #1 Auth plugin'
softdepend: [ProtocolLib]
commands:
  login:
    description: đăng nhập vào tài khoản của bạn
    usage: /login <password>
  register:
    description: tạo mật khẩu cho tài khoản
    usage: /register <password>
  changepassword:
    description: đổi mâtk khẩu cho tài khoản
    aliases: [changepass]
    usage: /changepass <old pass> <new pass>
  logout:
    description: đăng xuất khỏi tài khoản
    usage: /logout
  unregister:
    description: hủy đăng ký tài khoản
    usage: /unregister <current password>
  lac:
    description: LoginSecurity lệnh của ngưòi điều hành
    usage: /lac
permissions:
  ls.update:
    description: Notify player of available updates
    default: op
  ls.bypass:
    description: Bypass registration requirement
    default: false
